background            #1A1A1D

color0                #1A1A1D
color1                #E1B6FF
color2                #FFFFFF
color3                #FFFFFF
color4                #D9EDFF
color5                #F1E6FF
color6                #FFFFFF
color7                #FFFFFF
color8                #FFFFFF
color9                #FFFFFF
color10               #FFFFFF
color11               #FFFFFF
color12               #FFFFFF
color13               #FFFFFF
color14               #FFFFFF
color15               #E0E3E8

color232              #FFFFFF

cursor                #FFFFFF

foreground            #FFFFFF

selection_background  #E1E2EC
selection_foreground  #44474F

# Override obscure colors for starship prompt (these are greys at the end)
color255              #C2C6D6
color254              #424753
color253              #C4C6D0
color252              #44474F
color251              #BFC6DC
color250              #8991A5
color249              #FFB4AB
color248              #93000A

color232              #2B303C
color233              #DEE2F2
color234              #2E3038
color235              #E1E2EC
color236              #293041
color237              #000000
color238              #690005
color239              #FFDAD6

color244              #929092
color245              #474648
